apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-store-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-store-api
  template:
    metadata:
      labels:
        app: car-store-api
    spec:
      containers:
        - name: car-store-api
          image: car-store-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: car-store-api-config
                  key: NODE_ENV
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: car-store-api-secret
                  key: SECRET_KEY 